### PR TITLE
add optional monitoring setup (prometheus, monero-exporter, grafana)

### PR DESCRIPTION
**Pull request by lalanza808**
cool project. this PR includes extra services for "Monitoring" selection with some open source tools.

prometheus and grafana are pretty much off the shelf using their container images.

the exporter is from `github.com/cirocosta/monero-exporter` - I used this dockerfile from my own project: https://github.com/lalanza808/docker-monero-node/blob/master/dockerfiles/monerod_exporter

the files fetched from wget are from that same project for the default prom and graf configs/dashboards: https://github.com/lalanza808/docker-monero-node/tree/master/files

The finished product looks like this https://singapore.node.xmr.pm

I did some light testing and appears to work as expected.

### CODE REVIEW

**Comment by hundehausen** [comment]
Hey @lalanza808!

Thank you for the first PR for Monero Suite!
I love your idea, and I had already planned to do something similar with the [monerod-exporter](https://github.com/hundehausen/monerod-exporter) I have written for Prometheus, but yours seems much more powerful.

For the future I am planning to add a reverse proxy with automatic let's encrypt like caddy or traeffik.

I will heavily test your PR, before merging it, that could take some time.

Also, are you fine with using the "latest" tag for versioning images? It's like this for the other services, too. Move fast and break things :D

**Comment by lalanza808** [comment]
we can thank @cirocosta for his work on the exporter - happy to use yours, but without certain metrics the dashboards might break. can always rework it thought.

I have some boilerplate stuff for traefik...i can make a PR if they look alright. 

latest tag is cool w/ me.... fail fast is excellent, devops ftw

happy to contribute

**Comment by hundehausen** [comment]
Hey @lalanza808,

could you update your branch to resolve merge conflicts?

**Comment by lalanza808** [comment]
yes - should I also update with my latest changes including the nodemapper w/ geoip map?

**Comment by hundehausen** [comment]
Yes, please make sure to pull my latest additions to your branch

**Comment by hundehausen** [comment]
I implemented and tested your project. It's live now ;) Thank you so much, I love it!

Can we get stats from P2Pool as well?

**Pull request merged**
